# Generated by Django 4.0.3 on 2022-03-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='mobile',
            field=models.CharField(default=1090802802, max_length=11),
            preserve_default=False,
        ),
    ]
